# react-nginx.sh — shared by install-production.sh and update.sh (sourced, not run).
#
# write_react_nginx_conf: the nginx server block that serves the React build for one tenant at
# FRONTEND_DOMAIN and proxies the backend surface to the bench, always for that tenant's site.
#
# The React build is site-agnostic (nothing in it names a site), so several tenants can serve the
# same FRONTEND_DIR/dist: the site is chosen here, by X-Frappe-Site-Name on every proxied location —
# including /socket.io, which otherwise falls back to the bench's default site (realtime for the
# wrong tenant).
#
# Needs: SITE_NAME, FRONTEND_DOMAIN, FRONTEND_DIR. Writes /etc/nginx/conf.d/${SITE_NAME}-react.conf
# (override with REACT_NGINX_CONF). Caller tests and reloads nginx, then calls restore_react_https.

write_react_nginx_conf() {
  local conf="${REACT_NGINX_CONF:-/etc/nginx/conf.d/${SITE_NAME}-react.conf}"
  local backend="${BACKEND_UPSTREAM:-127.0.0.1:8000}"     # bench setup production's gunicorn
  local socketio="${SOCKETIO_UPSTREAM:-127.0.0.1:9000}"   # bench's socketio
  local up="${SITE_NAME//[^A-Za-z0-9_]/_}"                 # upstream names allow no dots

  # certbot writes its HTTPS lines into this file; remember them so restore_react_https can put the
  # same certificate back after the rewrite (otherwise a re-run silently drops HTTPS).
  REACT_HAD_SSL=""
  if [[ -f "$conf" ]]; then
    grep -q "ssl_certificate" "$conf" && REACT_HAD_SSL=1
    cp "$conf" "${conf}.bak.$(date +%Y%m%d%H%M%S)"
  fi
  cat > "$conf" <<EOF
# Generated by react-nginx.sh for tenant site '${SITE_NAME}' — React app at ${FRONTEND_DOMAIN}.
upstream ${up}_backend {
    server ${backend} fail_timeout=0;
}
upstream ${up}_socketio {
    server ${socketio} fail_timeout=0;
}

server {
    listen 80;
    server_name ${FRONTEND_DOMAIN};

    root ${FRONTEND_DIR}/dist;
    index index.html;
    client_max_body_size 50m;

    # The React bundle's own /assets first; anything else under /assets is a Frappe app's static file.
    location /assets/ {
        try_files \$uri @backend;
    }

    location ~ ^/(api|files|private)/ {
        proxy_pass http://${up}_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Frappe-Site-Name ${SITE_NAME};
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 240;
        proxy_set_header X-Use-X-Accel-Redirect True;
    }

    # micromax: desk passthrough — /app (desk, POS Awesome) and /printview (print) served by Frappe
    location ~ ^/(app|printview)(/|$) {
        proxy_pass http://${up}_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Frappe-Site-Name ${SITE_NAME};
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 240;
    }

    location /socket.io/ {
        proxy_pass http://${up}_socketio;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Frappe-Site-Name ${SITE_NAME};
    }

    location @backend {
        proxy_pass http://${up}_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Frappe-Site-Name ${SITE_NAME};
    }

    # React Router — anything not matched above falls back to the SPA shell.
    location / {
        try_files \$uri /index.html;
    }
}
EOF
  echo "$conf"
}

# Re-install the existing Let's Encrypt certificate into the rewritten block (no new issuance).
restore_react_https() {
  [[ -n "${REACT_HAD_SSL:-}" ]] || return 0
  if command -v certbot >/dev/null; then
    echo "Re-applying the existing HTTPS certificate for ${FRONTEND_DOMAIN}"
    certbot --nginx -d "$FRONTEND_DOMAIN" --reinstall --redirect --non-interactive \
      || echo "WARN: certbot could not re-apply HTTPS — run: sudo certbot --nginx -d ${FRONTEND_DOMAIN}" >&2
  else
    echo "WARN: ${FRONTEND_DOMAIN} had HTTPS but certbot isn't installed — re-add the certificate by hand." >&2
  fi
}

# A tenant that had no React app had FRONTEND_DOMAIN mapped straight to its Frappe site
# (bench setup add-domain). Once the React app takes that domain, the mapping must go, or bench's
# generated nginx and the React block both claim the same server_name.
unmap_frontend_domain_from_site() {
  local cfg="${BENCH_DIR}/sites/${SITE_NAME}/site_config.json"
  if [[ -f "$cfg" ]] && grep -q "\"${FRONTEND_DOMAIN}\"" "$cfg"; then
    echo "Removing ${FRONTEND_DOMAIN} from site '${SITE_NAME}' domains — the React app serves it now"
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup remove-domain '$FRONTEND_DOMAIN' --site '$SITE_NAME'"
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup nginx --yes"
  fi
}

# The Let's Encrypt folder whose certificate covers $1. certbot names a folder after the FIRST domain on
# a certificate (or adds -0001), so a domain's certificate is often not in live/<domain>/: match the
# certificate's names instead. Prints the folder (no trailing slash), or nothing.
find_le_cert_dir() {
  local domain="$1" d
  for d in /etc/letsencrypt/live/*/; do
    [[ -f "${d}cert.pem" ]] || continue
    if openssl x509 -in "${d}cert.pem" -noout -ext subjectAltName 2>/dev/null | grep -qE "DNS:${domain//./\\.}(,|\$)"; then
      echo "${d%/}"
      return 0
    fi
  done
}

# Map a Frappe desk domain to SITE_NAME in bench's own nginx (bench setup add-domain). When a Let's
# Encrypt certificate for it exists, the paths go into the site config too, so every later
# `bench setup nginx` writes HTTPS itself — certbot's own edits to frappe-bench.conf don't survive
# a regeneration. A plain mapping is upgraded once a certificate exists. Prints "changed" when the
# site config changed (caller then runs `bench setup nginx` and reloads).
map_desk_domain() {
  local domain="$1"
  local cfg="${BENCH_DIR}/sites/${SITE_NAME}/site_config.json"
  local live
  live="$(find_le_cert_dir "$domain")"
  local state
  state="$(python3 - "$cfg" "$domain" <<'PY'
import json, sys
cfg, domain = sys.argv[1], sys.argv[2]
try:
    domains = json.load(open(cfg)).get("domains", [])
except FileNotFoundError:
    domains = []
for d in domains:
    if isinstance(d, dict) and d.get("domain") == domain:
        print("ssl " + (d.get("ssl_certificate") or "")); break
    if d == domain:
        print("plain"); break
else:
    print("none")
PY
)"
  local current_cert="${state#ssl }"
  [[ "$state" == ssl* ]] && state="ssl"
  if [[ -n "$live" && -f "${live}/fullchain.pem" && -f "${live}/privkey.pem" ]]; then
    # Already mapped to this certificate: nothing to do. Mapped to another path (e.g. a folder that
    # doesn't exist, which makes `nginx -t` fail): re-map.
    [[ "$state" == "ssl" && "$current_cert" == "${live}/fullchain.pem" ]] && return 0
    [[ "$state" == "plain" || "$state" == "ssl" ]] && as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup remove-domain '$domain' --site '$SITE_NAME'" >/dev/null
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup add-domain '$domain' --site '$SITE_NAME' --ssl-certificate '${live}/fullchain.pem' --ssl-certificate-key '${live}/privkey.pem'" >/dev/null
    echo "changed"
  elif [[ "$state" == "ssl" && ! -f "$current_cert" ]]; then
    # Mapped to a certificate file that doesn't exist and no certificate covers the domain:
    # fall back to a plain mapping so nginx stays valid.
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup remove-domain '$domain' --site '$SITE_NAME'" >/dev/null
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup add-domain '$domain' --site '$SITE_NAME'" >/dev/null
    echo "changed"
  elif [[ "$state" == "none" ]]; then
    as_root_sh "cd '$BENCH_DIR' && '$BENCH_BIN' setup add-domain '$domain' --site '$SITE_NAME'" >/dev/null
    echo "changed"
  fi
}
