import { BellRing, CalendarClock, GitBranch, Mail, Repeat, Shuffle, Users, Workflow as WorkflowIcon } from "lucide-react";
import type { DocConfig } from "@/components/doc/doc-config";
import {
  sec, colBreak, tab, data, date, int, check, text, link, select, ro, req, when,
  nameCol, textCol, dateCol, yesNoCol, statusCol,
} from "@/components/doc/doc-helpers";

/* ============================================================================ Workflow (approvals) */

export const WORKFLOW_CONFIG: DocConfig = {
  doctype: "Workflow",
  base: "/approvals/workflows",
  singular: "Workflow",
  plural: "Approval Workflows",
  subtitle: "Multi-step approvals — who may move a document from one state to the next",
  icon: WorkflowIcon,
  companyScoped: false,
  listFields: ["name", "workflow_name", "document_type", "is_active", "send_email_alert", "modified"],
  columns: [nameCol("Workflow", (r) => r.document_type), yesNoCol("is_active", "Status", "Active", "Inactive"), yesNoCol("send_email_alert", "Email Alerts", "On", "Off"), dateCol("modified", "Updated")],
  searchFields: ["name", "workflow_name", "document_type"],
  fields: [
    tab("Workflow"),
    sec("Workflow"),
    req(data("workflow_name", "Workflow Name")),
    req(link("document_type", "Document Type", "DocType")),
    req(data("workflow_state_field", "State Field")),
    colBreak(),
    check("is_active", "Is Active"),
    check("override_status", "Don't Override Status"),
    check("send_email_alert", "Send Email Alert"),
    check("enable_action_confirmation", "Confirm Before Actions"),
    tab("States"),
    tab("Transitions"),
  ],
  children: [
    {
      tab: "States",
      key: "states",
      label: "States",
      description: "Each state, the document status it maps to, and who may edit in it.",
      doctype: "Workflow Document State",
      wide: true,
      columns: [req(link("state", "State", "Workflow State")), select("doc_status", "Doc Status", ["0", "1", "2"]), req(link("allow_edit", "Only Editable By", "Role")),
        data("update_field", "Update Field"), data("update_value", "Update Value"), check("send_email", "Send Email")],
      dialogColumns: [link("next_action_email_template", "Email Template", "Email Template"), check("is_optional_state", "Optional State"), text("message", "Message")],
      newRow: () => ({ doc_status: "0", send_email: 1 }),
    },
    {
      tab: "Transitions",
      key: "transitions",
      label: "Transition Rules",
      description: "From state → action → next state, and the role allowed to take it.",
      doctype: "Workflow Transition",
      wide: true,
      columns: [req(link("state", "From State", "Workflow State")), req(link("action", "Action", "Workflow Action Master")), req(link("next_state", "Next State", "Workflow State")),
        req(link("allowed", "Allowed Role", "Role")), check("allow_self_approval", "Self Approval")],
      dialogColumns: [check("send_email_to_creator", "Email the Creator"), text("condition", "Condition (Python)")],
      newRow: () => ({ allow_self_approval: 1 }),
    },
  ],
  tabIcons: { Workflow: WorkflowIcon, States: GitBranch, Transitions: Shuffle },
  defaults: () => ({ is_active: 1, workflow_state_field: "workflow_state", send_email_alert: 1 }),
  summary: (v, rows) => [
    { label: "Status", value: v.is_active ? "Active" : "Inactive", tone: v.is_active ? "emerald" : "rose" },
    { label: "States", value: (rows.states ?? []).length, tone: "sky" },
    { label: "Transitions", value: (rows.transitions ?? []).length, tone: "indigo" },
  ],
  titleOf: (v) => v.workflow_name || "New Workflow",
};

/* ============================================================================ Notification (alerts) */

export const NOTIFICATION_CONFIG: DocConfig = {
  doctype: "Notification",
  base: "/approvals/notifications",
  singular: "Notification",
  plural: "Alerts & Notifications",
  subtitle: "Email, system and WhatsApp alerts on document events and due dates",
  icon: BellRing,
  companyScoped: false,
  listFields: ["name", "subject", "document_type", "event", "channel", "enabled", "modified"],
  columns: [nameCol("Notification", (r) => r.subject), textCol("document_type", "Document"), statusCol("event", "Event", "—"), textCol("channel", "Channel"), yesNoCol("enabled", "Status", "Enabled", "Disabled")],
  searchFields: ["name", "subject", "document_type"],
  statusField: "channel",
  statuses: ["Email", "System Notification", "WhatsApp", "SMS", "Slack"],
  fields: [
    tab("Trigger"),
    sec("When"),
    when(req(data("__newname", "Name")), (v) => !v.name),
    req(link("document_type", "Document Type", "DocType")),
    req(select("event", "Send Alert On", ["", "New", "Save", "Submit", "Cancel", "Days After", "Days Before", "Minutes After", "Minutes Before", "Value Change", "Method", "Custom"])),
    when(data("date_changed", "Reference Date Field"), (v) => ["Days After", "Days Before"].includes(v.event)),
    when(int("days_in_advance", "Days Before or After"), (v) => ["Days After", "Days Before"].includes(v.event)),
    when(data("value_changed", "Value Changed (field)"), (v) => v.event === "Value Change"),
    when(data("method", "Trigger Method"), (v) => v.event === "Method"),
    colBreak(),
    req(select("channel", "Channel", ["Email", "Slack", "System Notification", "SMS", "WhatsApp"])),
    check("enabled", "Enabled"),
    link("module", "Module", "Module Def"),
    sec("Condition"),
    select("condition_type", "Condition Type", ["Python", "Filters"]),
    colBreak(),
    text("condition", "Condition"),
    tab("Recipients"),
    sec("Who"),
    check("send_to_all_assignees", "Send to All Assignees"),
    colBreak(),
    when(link("sender", "Sender", "Email Account"), (v) => v.channel === "Email"),
    tab("Message"),
    sec("Message"),
    data("subject", "Subject"),
    select("message_type", "Message Type", ["Markdown", "HTML", "Plain Text"]),
    text("message", "Message"),
    sec("Attachment"),
    check("attach_print", "Attach Print"),
    colBreak(),
    when(link("print_format", "Print Format", "Print Format"), (v) => Boolean(v.attach_print)),
  ],
  children: [
    {
      tab: "Recipients",
      key: "recipients",
      label: "Recipients",
      doctype: "Notification Recipient",
      columns: [data("receiver_by_document_field", "Document Field (email / user)"), link("receiver_by_role", "Role", "Role"), text("cc", "CC"), data("condition", "Condition")],
    },
  ],
  tabIcons: { Trigger: BellRing, Recipients: Users, Message: Mail },
  defaults: () => ({ enabled: 1, channel: "Email", event: "New", condition_type: "Python", message_type: "Markdown" }),
  titleOf: (v) => (v.name ? String(v.name) : "New Notification"),
};

/* ============================================================================ Assignment Rule */

export const ASSIGNMENT_RULE_CONFIG: DocConfig = {
  doctype: "Assignment Rule",
  base: "/approvals/assignment-rules",
  singular: "Assignment Rule",
  plural: "Assignment Rules",
  subtitle: "Route new documents to people automatically — round robin, load balancing or by field",
  icon: Shuffle,
  companyScoped: false,
  listFields: ["name", "document_type", "rule", "priority", "disabled", "modified"],
  columns: [nameCol("Rule", (r) => r.document_type), textCol("rule", "Method"), textCol("priority", "Priority"), yesNoCol("disabled", "Status", "Disabled", "Enabled")],
  searchFields: ["name", "document_type"],
  fields: [
    tab("Rule"),
    sec("Rule"),
    when(req(data("__newname", "Name")), (v) => !v.name),
    req(link("document_type", "Document Type", "DocType")),
    req(text("description", "Description")),
    colBreak(),
    int("priority", "Priority"),
    check("disabled", "Disabled"),
    select("due_date_based_on", "Due Date Based On", [""]),
    sec("Conditions"),
    req(text("assign_condition", "Assign When (Python)")),
    colBreak(),
    text("unassign_condition", "Unassign When"),
    text("close_condition", "Close When"),
    tab("Assignees"),
    sec("Method"),
    req(select("rule", "Rule", ["Round Robin", "Load Balancing", "Based on Field", "Weighted Distribution"])),
    when(data("field", "Field"), (v) => v.rule === "Based on Field"),
    colBreak(),
    ro(link("last_user", "Last Assigned To", "User")),
  ],
  children: [
    { tab: "Assignees", key: "assignment_days", label: "Active Days", doctype: "Assignment Rule Day", minRows: 1,
      columns: [req(select("day", "Day", ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]))] },
    { tab: "Assignees", key: "users", label: "Users", doctype: "Assignment Rule User", columns: [req(link("user", "User", "User"))] },
  ],
  tabIcons: { Rule: Shuffle, Assignees: Users },
  defaults: () => ({ rule: "Round Robin", priority: 0 }),
  titleOf: (v) => (v.name ? String(v.name) : "New Assignment Rule"),
};

/* ============================================================================ Auto Repeat */

export const AUTO_REPEAT_CONFIG: DocConfig = {
  doctype: "Auto Repeat",
  base: "/approvals/auto-repeats",
  singular: "Auto Repeat",
  plural: "Recurring Documents",
  subtitle: "Documents copied on a schedule — monthly rent invoices, recurring journal entries",
  icon: Repeat,
  companyScoped: false,
  listFields: ["name", "reference_doctype", "reference_document", "frequency", "start_date", "end_date", "next_schedule_date", "disabled", "modified"],
  columns: [nameCol("Auto Repeat", (r) => `${r.reference_doctype} · ${r.reference_document}`), statusCol("frequency", "Frequency", "—"), dateCol("next_schedule_date", "Next"), dateCol("end_date", "Ends"), yesNoCol("disabled", "Status", "Disabled", "Active")],
  searchFields: ["name", "reference_doctype", "reference_document"],
  fields: [
    tab("Document"),
    sec("Source"),
    req(link("reference_doctype", "Document Type", "DocType")),
    req(data("reference_document", "Reference Document")),
    colBreak(),
    check("submit_on_creation", "Submit on Creation"),
    check("disabled", "Disabled"),
    tab("Schedule"),
    sec("Schedule"),
    req(select("frequency", "Frequency", ["", "Daily", "Weekly", "Fortnightly", "Monthly", "Quarterly", "Half-yearly", "Yearly"])),
    req(date("start_date", "Start Date")),
    date("end_date", "End Date"),
    colBreak(),
    int("repeat_on_day", "Repeat on Day of Month"),
    check("repeat_on_last_day", "Repeat on Last Day of Month"),
    ro(date("next_schedule_date", "Next Schedule Date")),
    tab("Notification"),
    sec("Email"),
    check("notify_by_email", "Notify by Email"),
    when(text("recipients", "Recipients"), (v) => Boolean(v.notify_by_email)),
    colBreak(),
    when(data("subject", "Subject"), (v) => Boolean(v.notify_by_email)),
    when(text("message", "Message"), (v) => Boolean(v.notify_by_email)),
  ],
  tabIcons: { Document: CalendarClock, Schedule: Repeat, Notification: Mail },
  defaults: () => ({ frequency: "Monthly" }),
  titleOf: (v) => (v.name ? `${v.name} · ${v.reference_document ?? ""}` : "New Auto Repeat"),
};

export const APPROVAL_CONFIGS = [WORKFLOW_CONFIG, NOTIFICATION_CONFIG, ASSIGNMENT_RULE_CONFIG, AUTO_REPEAT_CONFIG];
