import { Barcode, Boxes, ClipboardCheck, ClipboardList, Hash, MapPin, PackageSearch, Scale, Tag, Warehouse as WarehouseIcon } from "lucide-react";
import type { DocConfig } from "@/components/doc/doc-config";
import {
  sec, colBreak, tab, data, date, float, int, currency, check, text, link, select, ro, req,
  nameCol, textCol, dateCol, numCol, moneyCol, statusCol, yesNoCol, fmt, fmtMoney,
} from "@/components/doc/doc-helpers";
import { todayISO } from "@/utils/dates";
import { asNumber } from "@/utils/cn";

/* ============================================================================ Stock balance (Bin) */

export const STOCK_BALANCE_CONFIG: DocConfig = {
  doctype: "Bin",
  base: "/inventory/stock",
  singular: "Stock Balance",
  plural: "Stock Balance",
  subtitle: "On hand, reserved, ordered and projected quantity per item and warehouse",
  icon: PackageSearch,
  companyScoped: false,
  connections: false,
  listFields: ["name", "item_code", "warehouse", "actual_qty", "reserved_qty", "ordered_qty", "projected_qty", "valuation_rate", "stock_value", "stock_uom", "modified"],
  columns: [
    { key: "item_code", label: "Item", render: (r: any) => <div className="flex flex-col"><span className="font-medium">{r.item_code}</span><span className="text-xs text-muted-foreground">{r.warehouse}</span></div> },
    numCol("actual_qty", "On Hand", 2),
    numCol("reserved_qty", "Reserved", 2),
    numCol("ordered_qty", "On Order", 2),
    numCol("projected_qty", "Projected", 2),
    moneyCol("valuation_rate", "Valuation Rate"),
    moneyCol("stock_value", "Stock Value"),
  ],
  searchFields: ["item_code", "warehouse"],
  sort: { key: "stock_value", dir: "desc" },
  filters: [{ field: "warehouse", label: "Warehouse", optionsFrom: "Warehouse" }],
  fields: [
    tab("Balance"),
    sec("Item"),
    ro(link("item_code", "Item", "Item")),
    ro(link("warehouse", "Warehouse", "Warehouse")),
    colBreak(),
    ro(link("stock_uom", "UOM", "UOM")),
    sec("Quantities"),
    ro(float("actual_qty", "On Hand")),
    ro(float("reserved_qty", "Reserved for Sales")),
    ro(float("reserved_qty_for_production", "Reserved for Production")),
    colBreak(),
    ro(float("ordered_qty", "On Purchase Order")),
    ro(float("indented_qty", "Requested")),
    ro(float("planned_qty", "Planned (Work Orders)")),
    ro(float("projected_qty", "Projected")),
    sec("Value"),
    ro(currency("valuation_rate", "Valuation Rate")),
    colBreak(),
    ro(currency("stock_value", "Stock Value")),
  ],
  summary: (v) => [
    { label: "On hand", value: `${fmt(v.actual_qty)} ${v.stock_uom ?? ""}`, tone: "sky" },
    { label: "Projected", value: fmt(v.projected_qty), tone: asNumber(v.projected_qty) < 0 ? "rose" : "emerald" },
    { label: "Stock value", value: fmtMoney(v.stock_value), tone: "indigo" },
  ],
  titleOf: (v) => (v.item_code ? `${v.item_code} @ ${v.warehouse}` : "Stock Balance"),
};

/* ============================================================================ Warehouse */

export const WAREHOUSE_CONFIG: DocConfig = {
  doctype: "Warehouse",
  base: "/inventory/warehouses",
  singular: "Warehouse",
  plural: "Warehouses",
  subtitle: "Godowns, mill floors, WIP, finished-goods and third-party stores",
  icon: WarehouseIcon,
  listFields: ["name", "warehouse_name", "parent_warehouse", "is_group", "warehouse_type", "company", "account", "modified"],
  columns: [nameCol("Warehouse", (r) => r.parent_warehouse), textCol("warehouse_type", "Type"), yesNoCol("is_group", "Kind", "Group", "Store"), textCol("account", "Account")],
  searchFields: ["name", "warehouse_name", "parent_warehouse"],
  fields: [
    tab("Warehouse"),
    sec("Warehouse"),
    req(data("warehouse_name", "Warehouse Name")),
    req(link("company", "Company", "Company")),
    link("parent_warehouse", "Parent Warehouse", "Warehouse"),
    colBreak(),
    check("is_group", "Is Group"),
    check("is_rejected_warehouse", "Rejected Warehouse"),
    link("warehouse_type", "Warehouse Type", "Warehouse Type"),
    link("account", "Stock Account", "Account"),
    sec("Transit"),
    link("default_in_transit_warehouse", "Default In-Transit Warehouse", "Warehouse"),
    colBreak(),
    link("customer", "Customer (third-party stock)", "Customer"),
    tab("Address"),
    sec("Contact"),
    data("phone_no", "Phone"),
    data("mobile_no", "Mobile"),
    colBreak(),
    data("address_line_1", "Address Line 1"),
    data("address_line_2", "Address Line 2"),
    data("city", "City"),
    data("state", "State"),
  ],
  tabIcons: { Warehouse: WarehouseIcon, Address: MapPin },
  defaults: ({ company }) => ({ company, is_group: 0 }),
  titleOf: (v) => v.warehouse_name || v.name || "New Warehouse",
};

/* ============================================================================ Stock Reconciliation */

export const STOCK_RECONCILIATION_CONFIG: DocConfig = {
  doctype: "Stock Reconciliation",
  base: "/inventory/reconciliations",
  singular: "Stock Reconciliation",
  plural: "Stock Reconciliations",
  subtitle: "Physical count vs books — opening stock and periodic stock-taking",
  icon: Scale,
  submittable: true,
  listFields: ["name", "purpose", "posting_date", "set_warehouse", "difference_amount", "docstatus", "modified"],
  columns: [nameCol("Reconciliation", (r) => r.purpose), dateCol("posting_date", "Date"), textCol("set_warehouse", "Warehouse"), moneyCol("difference_amount", "Difference")],
  searchFields: ["name", "purpose", "set_warehouse"],
  statusField: "purpose",
  statuses: ["Opening Stock", "Stock Reconciliation"],
  dateField: "posting_date",
  sort: { key: "posting_date", dir: "desc" },
  fields: [
    tab("Count"),
    sec("Count"),
    req(select("naming_series", "Series", ["MAT-RECO-.YYYY.-"])),
    req(link("company", "Company", "Company")),
    req(select("purpose", "Purpose", ["Opening Stock", "Stock Reconciliation"])),
    colBreak(),
    req(date("posting_date", "Posting Date")),
    data("posting_time", "Posting Time"),
    check("set_posting_time", "Edit Posting Date and Time"),
    link("set_warehouse", "Default Warehouse", "Warehouse"),
    tab("Items"),
    tab("Accounting"),
    sec("Accounting"),
    link("expense_account", "Difference Account", "Account"),
    req(link("cost_center", "Cost Center", "Cost Center")),
    colBreak(),
    ro(currency("difference_amount", "Difference Amount")),
  ],
  children: [{
    tab: "Items",
    key: "items",
    label: "Counted Items",
    description: "Counted quantity and rate; the difference to the books posts to the difference account.",
    doctype: "Stock Reconciliation Item",
    minRows: 1,
    wide: true,
    columns: [req(link("item_code", "Item", "Item")), ro(data("item_name", "Item Name")), req(link("warehouse", "Warehouse", "Warehouse")), float("qty", "Counted Qty"),
      currency("valuation_rate", "Valuation Rate"), ro(float("current_qty", "Book Qty")), ro(float("qty_diff", "Qty Diff")), ro(currency("amount_difference", "Value Diff"))],
    dialogColumns: [link("batch_no", "Batch", "Batch"), text("serial_no", "Serial No"), ro(currency("current_valuation_rate", "Book Rate")), ro(currency("amount", "Amount")), check("allow_zero_valuation_rate", "Allow Zero Valuation")],
    derive: (r) => ({ ...r, qty_diff: asNumber(r.qty) - asNumber(r.current_qty) }),
    newRow: (v) => ({ warehouse: v.set_warehouse }),
    totals: (rows) => [
      { label: "Qty diff", value: fmt(rows.reduce((s, r) => s + asNumber(r.qty) - asNumber(r.current_qty), 0)), align: "right" },
      { label: "Value diff", value: fmtMoney(rows.reduce((s, r) => s + asNumber(r.amount_difference), 0)), align: "right" },
    ],
  }],
  tabIcons: { Count: ClipboardCheck, Items: Boxes, Accounting: Scale },
  defaults: ({ company }) => ({ company, naming_series: "MAT-RECO-.YYYY.-", purpose: "Stock Reconciliation", posting_date: todayISO() }),
  summary: (v, rows) => [
    { label: "Items counted", value: (rows.items ?? []).length, tone: "sky" },
    { label: "Value difference", value: fmtMoney(v.difference_amount), tone: asNumber(v.difference_amount) < 0 ? "rose" : "emerald" },
  ],
  titleOf: (v) => (v.name ? `${v.name} · ${v.purpose ?? ""}` : "New Stock Reconciliation"),
};

/* ============================================================================ Item Price */

export const ITEM_PRICE_CONFIG: DocConfig = {
  doctype: "Item Price",
  base: "/inventory/item-prices",
  singular: "Item Price",
  plural: "Item Prices",
  subtitle: "Buying and selling rates per price list, customer or supplier",
  icon: Tag,
  companyScoped: false,
  listFields: ["name", "item_code", "item_name", "price_list", "price_list_rate", "currency", "uom", "buying", "selling", "valid_from", "valid_upto", "customer", "supplier", "modified"],
  columns: [nameCol("Item", (r) => r.item_name), textCol("price_list", "Price List"), moneyCol("price_list_rate", "Rate"), textCol("uom", "UOM"),
    yesNoCol("selling", "Side", "Selling", "Buying"), dateCol("valid_from", "Valid From"), dateCol("valid_upto", "Valid Upto")],
  searchFields: ["item_code", "item_name", "price_list", "customer", "supplier"],
  statusField: "price_list",
  statuses: ["Standard Selling", "Standard Buying"],
  fields: [
    tab("Price"),
    sec("Item"),
    req(link("item_code", "Item", "Item")),
    ro(data("item_name", "Item Name")),
    req(link("uom", "UOM", "UOM")),
    int("packing_unit", "Packing Unit"),
    colBreak(),
    req(link("price_list", "Price List", "Price List")),
    req(currency("price_list_rate", "Rate")),
    ro(link("currency", "Currency", "Currency")),
    sec("Validity"),
    date("valid_from", "Valid From"),
    colBreak(),
    date("valid_upto", "Valid Upto"),
    int("lead_time_days", "Lead Time (days)"),
    tab("Party"),
    sec("Only for"),
    link("customer", "Customer", "Customer"),
    link("supplier", "Supplier", "Supplier"),
    colBreak(),
    link("batch_no", "Batch", "Batch"),
    sec("Notes"),
    text("note", "Note"),
    data("reference", "Reference"),
  ],
  tabIcons: { Price: Tag, Party: ClipboardList },
  defaults: () => ({ valid_from: todayISO() }),
  titleOf: (v) => (v.item_code ? `${v.item_code} · ${v.price_list ?? ""}` : "New Item Price"),
};

/* ============================================================================ Batch / Serial No */

export const BATCH_CONFIG: DocConfig = {
  doctype: "Batch",
  base: "/inventory/batches",
  singular: "Batch",
  plural: "Batches",
  subtitle: "Lots of fibre or yarn tracked from receipt to dispatch",
  icon: Hash,
  companyScoped: false,
  listFields: ["name", "batch_id", "item", "item_name", "batch_qty", "stock_uom", "manufacturing_date", "expiry_date", "disabled", "modified"],
  columns: [nameCol("Batch", (r) => r.item_name || r.item), numCol("batch_qty", "Qty", 2), dateCol("manufacturing_date", "Made"), dateCol("expiry_date", "Expires"), yesNoCol("disabled", "Status", "Disabled", "Active")],
  searchFields: ["name", "item", "item_name"],
  fields: [
    sec("Batch"),
    req(data("batch_id", "Batch ID")),
    req(link("item", "Item", "Item")),
    ro(data("item_name", "Item Name")),
    colBreak(),
    ro(float("batch_qty", "Batch Qty")),
    date("manufacturing_date", "Manufacturing Date"),
    date("expiry_date", "Expiry Date"),
    check("disabled", "Disabled"),
    sec("Source"),
    ro(link("supplier", "Supplier", "Supplier")),
    colBreak(),
    ro(data("reference_name", "Source Document")),
    sec("Description"),
    text("description", "Description"),
  ],
  titleOf: (v) => v.batch_id || v.name || "New Batch",
};

export const SERIAL_NO_CONFIG: DocConfig = {
  doctype: "Serial No",
  base: "/inventory/serial-nos",
  singular: "Serial No",
  plural: "Serial Numbers",
  subtitle: "Individually tracked units — machines, spares, cones",
  icon: Barcode,
  listFields: ["name", "item_code", "item_name", "warehouse", "status", "company", "warranty_expiry_date", "modified"],
  columns: [nameCol("Serial No", (r) => r.item_name || r.item_code), textCol("warehouse", "Warehouse"), dateCol("warranty_expiry_date", "Warranty"), statusCol("status", "Status", "Active")],
  searchFields: ["name", "item_code", "item_name", "warehouse"],
  statusField: "status",
  statuses: ["Active", "Inactive", "Consumed", "Delivered", "Expired"],
  fields: [
    sec("Serial No"),
    req(data("serial_no", "Serial No")),
    req(link("item_code", "Item", "Item")),
    ro(data("item_name", "Item Name")),
    req(link("company", "Company", "Company")),
    colBreak(),
    ro(link("warehouse", "Warehouse", "Warehouse")),
    ro(link("batch_no", "Batch", "Batch")),
    ro(select("status", "Status", ["", "Active", "Inactive", "Consumed", "Delivered", "Expired"])),
    sec("Warranty / AMC"),
    date("warranty_expiry_date", "Warranty Expiry"),
    colBreak(),
    date("amc_expiry_date", "AMC Expiry"),
  ],
  titleOf: (v) => v.serial_no || v.name || "New Serial No",
};

/* ============================================================================ Pick List */

export const PICK_LIST_CONFIG: DocConfig = {
  doctype: "Pick List",
  base: "/inventory/pick-lists",
  singular: "Pick List",
  plural: "Pick Lists",
  subtitle: "What to pick from which bin — for deliveries and material transfers",
  icon: ClipboardList,
  submittable: true,
  listFields: ["name", "purpose", "customer", "work_order", "material_request", "per_delivered", "docstatus", "modified"],
  columns: [nameCol("Pick List", (r) => r.purpose), textCol("customer", "Customer"), textCol("work_order", "Work Order"), numCol("per_delivered", "% Delivered", 1)],
  searchFields: ["name", "customer", "work_order", "material_request"],
  statusField: "purpose",
  statuses: ["Delivery", "Material Transfer", "Material Transfer for Manufacture"],
  fields: [
    tab("Pick List"),
    sec("Purpose"),
    req(link("company", "Company", "Company")),
    req(select("naming_series", "Series", ["STO-PICK-.YYYY.-"])),
    select("purpose", "Purpose", ["Material Transfer for Manufacture", "Material Transfer", "Delivery"]),
    colBreak(),
    link("customer", "Customer", "Customer"),
    link("parent_warehouse", "Warehouse", "Warehouse"),
    check("pick_manually", "Pick Manually"),
    sec("Reference"),
    link("work_order", "Work Order", "Work Order"),
    colBreak(),
    link("material_request", "Material Request", "Material Request"),
    tab("Locations"),
  ],
  children: [{
    tab: "Locations",
    key: "locations",
    label: "Pick Locations",
    doctype: "Pick List Item",
    wide: true,
    columns: [req(link("item_code", "Item", "Item")), ro(data("item_name", "Item Name")), link("warehouse", "Warehouse", "Warehouse"), req(float("qty", "Qty")), float("picked_qty", "Picked"), link("batch_no", "Batch", "Batch"), ro(float("actual_qty", "Available"))],
    totals: (rows) => [{ label: "To pick", value: fmt(rows.reduce((s, r) => s + asNumber(r.qty), 0)), align: "right" }, { label: "Picked", value: fmt(rows.reduce((s, r) => s + asNumber(r.picked_qty), 0)), align: "right" }],
  }],
  tabIcons: { "Pick List": ClipboardList, Locations: MapPin },
  defaults: ({ company }) => ({ company, naming_series: "STO-PICK-.YYYY.-", purpose: "Material Transfer for Manufacture" }),
  titleOf: (v) => (v.name ? `${v.name} · ${v.purpose ?? ""}` : "New Pick List"),
};

export const STOCK_CONFIGS = [STOCK_BALANCE_CONFIG, WAREHOUSE_CONFIG, STOCK_RECONCILIATION_CONFIG, ITEM_PRICE_CONFIG, BATCH_CONFIG, SERIAL_NO_CONFIG, PICK_LIST_CONFIG];
