import { BadgeDollarSign, Barcode, Boxes, Building2, Factory, FileText, Globe, Landmark, Layers, MapPin, Receipt, Settings2, ShoppingBag, ShoppingCart, Ship, Truck, Users, Warehouse } from "lucide-react";
import type { ChildTableSpec, DocConfig, ExtraContext } from "@/components/doc/doc-config";
import {
  sec, colBreak, tab, data, date, float, int, currency, check, text, richText, link, select, ro, req, when,
  nameCol, textCol, moneyCol, yesNoCol, fmt,
} from "@/components/doc/doc-helpers";
import { asNumber } from "@/utils/cn";
import { MasterInsightsPanel } from "./master-insights-panel";

const insights = (doctype: string) => (ctx: ExtraContext) => <MasterInsightsPanel {...ctx} doctype={doctype} />;
const saved = (v: Record<string, any>) => Boolean(v.creation);

/* ---------------------------------------------------------------- shared child tables */
const PARTY_ACCOUNTS = (tabLabel: string, label = "Default Accounts"): ChildTableSpec => ({
  tab: tabLabel,
  key: "accounts",
  label,
  description: "Receivable / payable and advance accounts per company (blank = company default).",
  doctype: "Party Account",
  columns: [req(link("company", "Company", "Company")), link("account", "Account", "Account"), link("advance_account", "Advance Account", "Account")],
});
const CREDIT_LIMITS = (tabLabel: string): ChildTableSpec => ({
  tab: tabLabel,
  key: "credit_limits",
  label: "Credit Limits",
  description: "Sales orders and invoices are blocked beyond this outstanding, unless bypassed.",
  doctype: "Customer Credit Limit",
  columns: [link("company", "Company", "Company"), currency("credit_limit", "Credit Limit"), check("bypass_credit_limit_check", "Bypass at Sales Order")],
});
const ALLOWED_COMPANIES = (tabLabel: string): ChildTableSpec => ({
  tab: tabLabel, key: "companies", label: "Allowed To Transact With", doctype: "Allowed To Transact With", columns: [req(link("company", "Company", "Company"))],
});
const ITEM_TAXES = (tabLabel: string): ChildTableSpec => ({
  tab: tabLabel,
  key: "taxes",
  label: "Item Tax",
  description: "Tax templates overriding the transaction's default for this item (sales tax, further tax, exemptions).",
  doctype: "Item Tax",
  columns: [req(link("item_tax_template", "Item Tax Template", "Item Tax Template")), link("tax_category", "Tax Category", "Tax Category"), date("valid_from", "Valid From"),
    float("minimum_net_rate", "Min Net Rate"), float("maximum_net_rate", "Max Net Rate")],
});
const ITEM_DEFAULTS = (tabLabel: string, key = "item_defaults"): ChildTableSpec => ({
  tab: tabLabel,
  key,
  label: "Defaults per Company",
  description: "Warehouse, supplier, price list, accounts and cost centres used when this item is picked on a transaction.",
  doctype: "Item Default",
  wide: true,
  columns: [req(link("company", "Company", "Company")), link("default_warehouse", "Default Warehouse", "Warehouse"), link("default_supplier", "Default Supplier", "Supplier"),
    link("default_price_list", "Price List", "Price List"), link("expense_account", "Expense Account", "Account"), link("income_account", "Income Account", "Account")],
  dialogColumns: [link("buying_cost_center", "Buying Cost Center", "Cost Center"), link("selling_cost_center", "Selling Cost Center", "Cost Center"),
    link("default_inventory_account", "Inventory Account", "Account"), link("default_cogs_account", "COGS Account", "Account"), link("default_discount_account", "Discount Account", "Account")],
});

/* ============================================================================ Item */

export const ITEM_CONFIG: DocConfig = {
  doctype: "Item",
  base: "/masters/items",
  singular: "Item",
  plural: "Items",
  subtitle: "Fibre, yarn, waste, spares and services — stock, buying, selling and manufacturing settings",
  icon: Boxes,
  companyScoped: false,
  listFields: ["name", "item_name", "item_group", "stock_uom", "valuation_rate", "is_stock_item", "disabled", "modified"],
  columns: [nameCol("Item", (r) => r.item_name), textCol("item_group", "Group"), textCol("stock_uom", "UOM"), moneyCol("valuation_rate", "Valuation Rate"), yesNoCol("disabled", "Status", "Disabled", "Enabled")],
  searchFields: ["name", "item_name", "item_group"],
  fields: [
    tab("Details"),
    sec("Item"),
    when(req(data("item_code", "Item Code")), (v) => !saved(v)),
    when(ro(data("item_code", "Item Code")), saved),
    data("item_name", "Item Name"),
    req(link("item_group", "Item Group", "Item Group")),
    req(link("stock_uom", "Default Unit of Measure", "UOM")),
    colBreak(),
    link("brand", "Brand", "Brand"),
    check("is_stock_item", "Maintain Stock"),
    check("is_fixed_asset", "Is Fixed Asset"),
    when(link("asset_category", "Asset Category", "Asset Category"), (v) => Boolean(v.is_fixed_asset)),
    check("has_variants", "Has Variants"),
    check("disabled", "Disabled"),
    sec("Allowed on"),
    check("is_purchase_item", "Purchase"),
    check("is_sales_item", "Sales"),
    colBreak(),
    check("is_customer_provided_item", "Customer-provided (conversion)"),
    check("allow_alternative_item", "Allow Alternative Item"),
    sec("Description"),
    richText("description", "Description"),

    tab("Inventory"),
    sec("Valuation"),
    select("valuation_method", "Valuation Method", ["", "FIFO", "Moving Average", "LIFO"]),
    currency("valuation_rate", "Valuation Rate"),
    colBreak(),
    select("default_material_request_type", "Default Material Request Type", ["Purchase", "Material Transfer", "Material Issue", "Manufacture", "Customer Provided"]),
    check("allow_negative_stock", "Allow Negative Stock"),
    sec("Weight & life"),
    float("weight_per_unit", "Weight Per Unit"),
    link("weight_uom", "Weight UOM", "UOM"),
    colBreak(),
    date("end_of_life", "End of Life"),
    data("warranty_period", "Warranty Period (days)"),
    sec("Batches & serial numbers"),
    check("has_batch_no", "Has Batch No"),
    when(check("create_new_batch", "Auto-create Batch"), (v) => Boolean(v.has_batch_no)),
    when(data("batch_number_series", "Batch Number Series"), (v) => Boolean(v.has_batch_no)),
    when(check("has_expiry_date", "Has Expiry Date"), (v) => Boolean(v.has_batch_no)),
    when(int("shelf_life_in_days", "Shelf Life (days)"), (v) => Boolean(v.has_batch_no)),
    colBreak(),
    check("has_serial_no", "Has Serial No"),
    when(data("serial_no_series", "Serial Number Series"), (v) => Boolean(v.has_serial_no)),

    tab("UOM & Barcodes"),
    sec("Packing"),
    link("packing_uom", "Packing UOM", "UOM"),
    colBreak(),
    float("packing_size", "Packing Size"),

    tab("Purchasing"),
    sec("Purchasing"),
    link("purchase_uom", "Purchase UOM", "UOM"),
    float("min_order_qty", "Minimum Order Qty"),
    float("safety_stock", "Safety Stock"),
    colBreak(),
    int("lead_time_days", "Lead Time (days)"),
    ro(float("last_purchase_rate", "Last Purchase Rate")),
    check("delivered_by_supplier", "Delivered by Supplier (drop ship)"),
    float("over_delivery_receipt_allowance", "Over Delivery/Receipt Allowance (%)"),

    tab("Sales"),
    sec("Selling"),
    link("sales_uom", "Sales UOM", "UOM"),
    currency("standard_rate", "Standard Selling Rate"),
    colBreak(),
    float("max_discount", "Max Discount (%)"),
    float("over_billing_allowance", "Over Billing Allowance (%)"),
    check("grant_commission", "Grant Commission"),

    tab("Manufacturing"),
    sec("Production"),
    ro(link("default_bom", "Default BOM", "BOM")),
    float("yield", "Yield %"),
    int("production_capacity", "Production Capacity"),
    colBreak(),
    check("include_item_in_manufacturing", "Include in Manufacturing"),
    check("is_sub_contracted_item", "Supply Raw Materials for Purchase (subcontracted)"),
    sec("Quality"),
    check("inspection_required_before_purchase", "Inspection Required before Purchase"),
    check("inspection_required_before_delivery", "Inspection Required before Delivery"),
    colBreak(),
    link("quality_inspection_template", "Inspection Template", "Quality Inspection Template"),

    tab("Accounting & Tax"),
    sec("Withholding"),
    link("purchase_tax_withholding_category", "Purchase Withholding Category", "Tax Withholding Category"),
    colBreak(),
    link("sales_tax_withholding_category", "Sales Withholding Category", "Tax Withholding Category"),

    tab("Trade"),
    sec("Customs"),
    data("hs_code", "HS Code"),
    link("customs_tariff_number", "Customs Tariff Number", "Customs Tariff Number"),
    link("country_of_origin", "Country of Origin", "Country"),
    float("import_duty_percent", "Import Duty %"),
    float("additional_duty_percent", "Additional Duty %"),
    colBreak(),
    link("export_uom", "Export UOM", "UOM"),
    select("packing_type", "Packing Type", ["", "Bale", "Carton", "Case", "Polybag", "Roll", "Other"]),
    float("net_weight_per_unit", "Net Weight / Unit"),
    float("gross_weight_per_unit", "Gross Weight / Unit"),
    data("fabric_material_composition", "Material Composition"),
    sec("Descriptions"),
    text("customs_description", "Customs Description"),
    colBreak(),
    text("commercial_description", "Commercial Description"),
  ],
  children: [
    { tab: "UOM & Barcodes", key: "uoms", label: "Unit Conversions", description: "e.g. 1 Bag = 100 Pound.", doctype: "UOM Conversion Detail",
      columns: [req(link("uom", "UOM", "UOM")), float("conversion_factor", "Conversion Factor (to stock UOM)")] },
    { tab: "UOM & Barcodes", key: "barcodes", label: "Barcodes", doctype: "Item Barcode",
      columns: [req(data("barcode", "Barcode")), select("barcode_type", "Type", ["", "EAN", "UPC-A", "CODE-39", "EAN-13", "EAN-8", "GS1", "GTIN", "GTIN-14", "ISBN"]), link("uom", "UOM", "UOM")] },
    { tab: "Inventory", key: "reorder_levels", label: "Auto Re-order", description: "Raise a material request when a warehouse falls below its level.", doctype: "Item Reorder",
      columns: [req(link("warehouse", "Warehouse", "Warehouse")), float("warehouse_reorder_level", "Re-order Level"), float("warehouse_reorder_qty", "Re-order Qty"),
        req(select("material_request_type", "Request Type", ["Purchase", "Transfer", "Material Issue", "Manufacture"]))],
      newRow: () => ({ material_request_type: "Purchase" }) },
    { tab: "Purchasing", key: "supplier_items", label: "Suppliers", description: "Approved suppliers and their part numbers.", doctype: "Item Supplier",
      columns: [req(link("supplier", "Supplier", "Supplier")), data("supplier_part_no", "Supplier Part No")] },
    { tab: "Sales", key: "customer_items", label: "Customer Codes", description: "How each customer refers to this item.", doctype: "Item Customer Detail",
      columns: [link("customer_name", "Customer", "Customer"), link("customer_group", "Customer Group", "Customer Group"), req(data("ref_code", "Customer Item Code"))] },
    ITEM_DEFAULTS("Accounting & Tax"),
    ITEM_TAXES("Accounting & Tax"),
  ],
  tabIcons: { Details: Boxes, Inventory: Warehouse, "UOM & Barcodes": Barcode, Purchasing: ShoppingCart, Sales: ShoppingBag, Manufacturing: Factory, "Accounting & Tax": Landmark, Trade: Ship },
  tabPanels: { Details: { before: insights("Item") } },
  defaults: () => ({ is_stock_item: 1, is_purchase_item: 1, is_sales_item: 1, include_item_in_manufacturing: 1 }),
  summary: (v) => [
    { label: "Valuation rate", value: fmt(v.valuation_rate), tone: "emerald" },
    { label: "Stock UOM", value: v.stock_uom || "—", tone: "sky" },
    { label: "Group", value: v.item_group || "—", tone: "indigo" },
  ],
  titleOf: (v) => (v.item_code ? `${v.item_code}${v.item_name && v.item_name !== v.item_code ? ` · ${v.item_name}` : ""}` : "New Item"),
};

/* ============================================================================ Customer / Supplier */

export const CUSTOMER_CONFIG: DocConfig = {
  doctype: "Customer",
  base: "/masters/customers",
  singular: "Customer",
  plural: "Customers",
  subtitle: "Yarn buyers and conversion customers — terms, credit, accounts and export details",
  icon: Users,
  companyScoped: false,
  listFields: ["name", "customer_name", "customer_group", "territory", "customer_type", "disabled", "modified"],
  columns: [nameCol("Customer", (r) => r.customer_name), textCol("customer_group", "Group"), textCol("territory", "Territory"), yesNoCol("disabled", "Status", "Disabled", "Active")],
  searchFields: ["name", "customer_name", "customer_group"],
  fields: [
    tab("Details"),
    sec("Customer"),
    req(data("customer_name", "Customer Name")),
    req(select("customer_type", "Customer Type", ["Company", "Individual", "Partnership"])),
    link("customer_group", "Customer Group", "Customer Group"),
    link("territory", "Territory", "Territory"),
    colBreak(),
    data("alias", "Alias"),
    link("account_manager", "Account Manager", "User"),
    check("disabled", "Disabled"),
    check("is_frozen", "Frozen (transactions blocked)"),
    sec("Defaults"),
    link("default_currency", "Default Currency", "Currency"),
    link("default_price_list", "Default Price List", "Price List"),
    colBreak(),
    link("payment_terms", "Default Payment Terms", "Payment Terms Template"),
    link("default_bank_account", "Default Bank Account", "Bank Account"),

    tab("Address & Contact"),
    sec("Primary"),
    link("customer_primary_address", "Primary Address", "Address"),
    ro(text("primary_address", "Address")),
    colBreak(),
    link("customer_primary_contact", "Primary Contact", "Contact"),
    ro(data("mobile_no", "Mobile")),
    ro(data("email_id", "Email")),

    tab("Accounting & Credit"),
    sec("Internal customer"),
    check("is_internal_customer", "Is Internal Customer"),
    colBreak(),
    when(link("represents_company", "Represents Company", "Company"), (v) => Boolean(v.is_internal_customer)),

    tab("Tax"),
    sec("Tax"),
    data("tax_id", "Tax ID / NTN"),
    link("tax_category", "Tax Category", "Tax Category"),
    colBreak(),
    link("tax_withholding_category", "Tax Withholding Category", "Tax Withholding Category"),

    tab("Sales Team"),
    sec("Partner"),
    link("default_sales_partner", "Default Sales Partner", "Sales Partner"),
    colBreak(),
    float("default_commission_rate", "Commission Rate (%)"),

    tab("Export"),
    sec("Buyer"),
    data("buyer_code", "Buyer Code"),
    link("buyer_country", "Buyer Country", "Country"),
    data("buyer_registration_no", "Registration No"),
    colBreak(),
    select("default_incoterm", "Default Incoterm", ["", "EXW", "FCA", "FAS", "FOB", "CFR", "CIF", "CPT", "CIP", "DAP", "DPU", "DDP"]),
    link("export_payment_terms", "Export Payment Terms", "Payment Terms Template"),
    check("export_license_requirement", "Export License Required"),
    sec("Shipping"),
    data("default_port_of_loading", "Port of Loading"),
    data("default_port_of_discharge", "Port of Discharge"),
    colBreak(),
    data("export_bank", "Export Bank"),
    data("beneficiary_ref", "Beneficiary Reference"),
    text("shipping_doc_requirement", "Shipping Document Requirements"),

    tab("Settings"),
    sec("Documents"),
    check("so_required", "Sales Order Required for Invoice / Delivery"),
    check("dn_required", "Delivery Note Required for Invoice"),
    colBreak(),
    link("language", "Print Language", "Language"),
    sec("More"),
    link("industry", "Industry", "Industry Type"),
    link("market_segment", "Market Segment", "Market Segment"),
    colBreak(),
    data("website", "Website"),
    ro(link("lead_name", "From Lead", "Lead")),
    sec("Notes"),
    text("customer_details", "Customer Details"),
  ],
  children: [
    PARTY_ACCOUNTS("Accounting & Credit"),
    CREDIT_LIMITS("Accounting & Credit"),
    ALLOWED_COMPANIES("Accounting & Credit"),
    { tab: "Sales Team", key: "sales_team", label: "Sales Team", doctype: "Sales Team",
      columns: [req(link("sales_person", "Sales Person", "Sales Person")), float("allocated_percentage", "Contribution (%)"), currency("incentives", "Incentives")],
      totals: (rows) => [{ label: "Allocated", value: `${fmt(rows.reduce((s, r) => s + asNumber(r.allocated_percentage), 0), 1)} %`, align: "right" }] },
  ],
  tabIcons: { Details: Users, "Address & Contact": MapPin, "Accounting & Credit": Landmark, Tax: Receipt, "Sales Team": BadgeDollarSign, Export: Ship, Settings: Settings2 },
  tabPanels: { Details: { before: insights("Customer") } },
  defaults: () => ({ customer_type: "Company" }),
  titleOf: (v) => v.customer_name || v.name || "New Customer",
};

export const SUPPLIER_CONFIG: DocConfig = {
  doctype: "Supplier",
  base: "/masters/suppliers",
  singular: "Supplier",
  plural: "Suppliers",
  subtitle: "Fibre mills, spares vendors, subcontractors and transporters",
  icon: Truck,
  companyScoped: false,
  listFields: ["name", "supplier_name", "supplier_group", "country", "supplier_type", "on_hold", "disabled", "modified"],
  columns: [nameCol("Supplier", (r) => r.supplier_name), textCol("supplier_group", "Group"), textCol("country", "Country"), yesNoCol("on_hold", "Hold", "On hold", "—"), yesNoCol("disabled", "Status", "Disabled", "Active")],
  searchFields: ["name", "supplier_name", "supplier_group"],
  fields: [
    tab("Details"),
    sec("Supplier"),
    req(data("supplier_name", "Supplier Name")),
    req(select("supplier_type", "Supplier Type", ["Company", "Individual", "Partnership"])),
    link("supplier_group", "Supplier Group", "Supplier Group"),
    link("country", "Country", "Country"),
    colBreak(),
    data("alias", "Alias"),
    check("is_transporter", "Is Transporter"),
    check("disabled", "Disabled"),
    check("is_frozen", "Frozen (transactions blocked)"),
    sec("Defaults"),
    link("default_currency", "Default Currency", "Currency"),
    link("default_price_list", "Default Price List", "Price List"),
    colBreak(),
    link("payment_terms", "Default Payment Terms", "Payment Terms Template"),
    link("default_bank_account", "Default Bank Account", "Bank Account"),

    tab("Address & Contact"),
    sec("Primary"),
    link("supplier_primary_address", "Primary Address", "Address"),
    ro(text("primary_address", "Address")),
    colBreak(),
    link("supplier_primary_contact", "Primary Contact", "Contact"),
    ro(data("mobile_no", "Mobile")),
    ro(data("email_id", "Email")),

    tab("Accounting"),
    sec("Internal supplier"),
    check("is_internal_supplier", "Is Internal Supplier"),
    colBreak(),
    when(link("represents_company", "Represents Company", "Company"), (v) => Boolean(v.is_internal_supplier)),

    tab("Tax"),
    sec("Tax"),
    data("tax_id", "Tax ID / NTN"),
    link("tax_category", "Tax Category", "Tax Category"),
    colBreak(),
    link("tax_withholding_category", "Tax Withholding Category", "Tax Withholding Category"),

    tab("Import"),
    sec("Import"),
    link("supplier_country", "Supplier Country", "Country"),
    data("supplier_import_code", "Import Code"),
    data("import_license_no", "Import License No"),
    link("clearing_agent", "Clearing Agent", "Supplier"),
    colBreak(),
    select("default_incoterm", "Default Incoterm", ["", "EXW", "FCA", "FAS", "FOB", "CFR", "CIF", "CPT", "CIP", "DAP", "DPU", "DDP"]),
    link("import_payment_terms", "Import Payment Terms", "Payment Terms Template"),
    data("bank_lc_reference", "Bank / LC Reference"),
    sec("Ports"),
    data("default_port_of_loading", "Port of Loading"),
    colBreak(),
    data("default_port_of_discharge", "Port of Discharge"),

    tab("Settings"),
    sec("Invoices"),
    check("allow_purchase_invoice_creation_without_purchase_order", "Allow Invoice without Purchase Order"),
    check("allow_purchase_invoice_creation_without_purchase_receipt", "Allow Invoice without Purchase Receipt"),
    colBreak(),
    link("language", "Print Language", "Language"),
    data("website", "Website"),
    sec("Hold"),
    check("on_hold", "Block Supplier"),
    when(select("hold_type", "Hold Type", ["All", "Invoices", "Payments"]), (v) => Boolean(v.on_hold)),
    colBreak(),
    when(date("release_date", "Release Date"), (v) => Boolean(v.on_hold)),
    sec("Notes"),
    text("supplier_details", "Supplier Details"),
  ],
  children: [PARTY_ACCOUNTS("Accounting"), ALLOWED_COMPANIES("Accounting")],
  tabIcons: { Details: Truck, "Address & Contact": MapPin, Accounting: Landmark, Tax: Receipt, Import: Globe, Settings: Settings2 },
  tabPanels: { Details: { before: insights("Supplier") } },
  defaults: () => ({ supplier_type: "Company" }),
  titleOf: (v) => v.supplier_name || v.name || "New Supplier",
};

/* ============================================================================ Groups */

const groupBase = (doctype: string, base: string, nameField: string, parentField: string, icon: DocConfig["icon"], subtitle: string): Omit<DocConfig, "fields" | "children"> => ({
  doctype,
  base,
  singular: doctype,
  plural: `${doctype}s`,
  subtitle,
  icon,
  companyScoped: false,
  listFields: ["name", parentField, "is_group", "modified"],
  columns: [nameCol(doctype, (r) => r[parentField]), yesNoCol("is_group", "Kind", "Group", "Leaf")],
  searchFields: ["name", parentField],
  tabPanels: { Details: { before: insights(doctype) } },
  titleOf: (v) => v[nameField] || v.name || `New ${doctype}`,
});

export const ITEM_GROUP_CONFIG: DocConfig = {
  ...groupBase("Item Group", "/masters/item-groups", "item_group_name", "parent_item_group", Layers, "Item tree — defaults and taxes inherited by the items below"),
  fields: [
    tab("Details"),
    sec("Group"),
    req(data("item_group_name", "Item Group Name")),
    link("parent_item_group", "Parent Item Group", "Item Group"),
    colBreak(),
    check("is_group", "Is Group"),
    tab("Defaults & Tax"),
  ],
  children: [ITEM_DEFAULTS("Defaults & Tax", "item_group_defaults"), ITEM_TAXES("Defaults & Tax")],
  tabIcons: { Details: Layers, "Defaults & Tax": Landmark },
};

export const CUSTOMER_GROUP_CONFIG: DocConfig = {
  ...groupBase("Customer Group", "/masters/customer-groups", "customer_group_name", "parent_customer_group", Building2, "Customer segments — default price list, terms, accounts and credit limits"),
  fields: [
    tab("Details"),
    sec("Group"),
    req(data("customer_group_name", "Customer Group Name")),
    link("parent_customer_group", "Parent Customer Group", "Customer Group"),
    check("is_group", "Is Group"),
    colBreak(),
    link("default_price_list", "Default Price List", "Price List"),
    link("payment_terms", "Default Payment Terms", "Payment Terms Template"),
    tab("Accounts & Credit"),
  ],
  children: [PARTY_ACCOUNTS("Accounts & Credit"), CREDIT_LIMITS("Accounts & Credit")],
  tabIcons: { Details: Building2, "Accounts & Credit": Landmark },
};

export const SUPPLIER_GROUP_CONFIG: DocConfig = {
  ...groupBase("Supplier Group", "/masters/supplier-groups", "supplier_group_name", "parent_supplier_group", FileText, "Supplier categories — default terms and payable accounts"),
  fields: [
    tab("Details"),
    sec("Group"),
    req(data("supplier_group_name", "Supplier Group Name")),
    link("parent_supplier_group", "Parent Supplier Group", "Supplier Group"),
    colBreak(),
    check("is_group", "Is Group"),
    link("payment_terms", "Default Payment Terms", "Payment Terms Template"),
    tab("Accounts"),
  ],
  children: [PARTY_ACCOUNTS("Accounts", "Default Payable Accounts")],
  tabIcons: { Details: FileText, Accounts: Landmark },
};
